2018-09-16 22:16:20,874 INFO: CodeNote startup [in /home/ubuntu/workspace/app/__init__.py:79]
2018-09-16 22:18:10,194 INFO: CodeNote startup [in /home/ubuntu/workspace/app/__init__.py:79]
2018-09-16 22:19:18,556 INFO: CodeNote startup [in /home/ubuntu/workspace/app/__init__.py:79]
2018-09-16 22:20:14,982 INFO: CodeNote startup [in /home/ubuntu/workspace/app/__init__.py:79]
2018-09-16 22:24:00,790 INFO: CodeNote startup [in /home/ubuntu/workspace/app/__init__.py:79]
2018-09-16 22:27:27,667 INFO: CodeNote startup [in /home/ubuntu/workspace/app/__init__.py:79]
2018-09-16 22:31:19,236 INFO: CodeNote startup [in /home/ubuntu/workspace/app/__init__.py:79]
2018-09-16 22:32:59,267 INFO: CodeNote startup [in /home/ubuntu/workspace/app/__init__.py:79]
2018-09-16 22:33:03,644 ERROR: Exception on /index [GET] [in /home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/ubuntu/workspace/app/main/routes.py", line 47, in index
    prev_url=prev_url)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/workspace/app/templates/base.html", line 171, in template
    {% endblock %}
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/ubuntu/workspace/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/workspace/app/templates/base.html", line 171, in template
    {% endblock %}
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/parser.py", line 170, in parse_statements
    self.fail_eof(end_tokens)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/parser.py", line 104, in fail_eof
    return self._fail_ut_eof(None, stack, lineno)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2018-09-16 22:34:01,626 INFO: CodeNote startup [in /home/ubuntu/workspace/app/__init__.py:79]
2018-09-16 22:34:04,817 ERROR: Exception on /index [GET] [in /home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/ubuntu/workspace/app/main/routes.py", line 47, in index
    prev_url=prev_url)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/workspace/app/templates/base.html", line 11, in template
    {% extends 'base.html' %}{% endblock %}
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/ubuntu/workspace/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/workspace/app/templates/base.html", line 11, in template
    {% extends 'base.html' %}{% endblock %}
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
2018-09-16 22:34:30,653 INFO: CodeNote startup [in /home/ubuntu/workspace/app/__init__.py:79]
